# Generated by Django 5.0.6 on 2024-06-20 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('HR', 'human resource'), ('IT', 'Information technology'), ('FINANCE', 'finance departments'), ('OPM', 'Operations Management'), ('OTHERS', 'Others')], max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_leave', models.CharField(choices=[('AL', 'Annual Leave'), ('SL', 'Sick Leave'), ('CL', 'Casual Leave'), ('ML', 'Maternity Leave'), ('PL', 'Paternity Leave'), ('MAL', 'Marriage Leave'), ('OTHERS', 'Others')], max_length=50)),
                ('reason', models.TextField()),
                ('first_day_of_absence', models.DateField()),
                ('last_day_of_absence', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_approval', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
